### ISSUE TITLE
How to import the the model in tensorrt python?

### ISSUE THREAD

**Issue by Narasimha1997** [NVIDIA/retinanet-examples#113]
Is there a guide / documentation available regarding how to convert the model into trt and load it in tensorrt python?

**Comment by yashnv** [comment]
For this project we just use the TensorRT C++ API to build the TensorRT engine plan(file) by parsing ONNX exported model. The instructions can be found in the README. In addition we also provide an example of C++ export and infer parts for this project for the ONNX exported model.
We use Pybind11 pytorch extensions to extend this C++ API so that it can be called from Python, thus avoiding to rewrite this again in Python TRT API. This implementation can be found in `csrc/extensions.cpp`

**Comment by Narasimha1997** [comment]
Cool, closing the issue as we were able to run retinanet._C engine directly.

**Comment by mialo-tech** [comment]
> Cool, closing the issue as we were able to run retinanet._C engine directly.

@Narasimha1997 Can you please explain the steps you have done. I'm trying to integrate the tensorrt model to my current python pipeline on Jetson nano.
