### ISSUE TITLE
How to make large batch inferences?

### ISSUE THREAD

**Issue by uCedar** [NVIDIA/retinanet-examples#137]
Hello, I'm using the C++ API and test the sample `infer.cpp` which located in `/retinanet-examples/tree/master/extras/cppapi`. how to infer one batch of images at the same time?  is there any examples?

**Comment by yashnv** [comment]
I don't understand your question What do you mean by?:
>> how to infer one batch of images at the same time?

The C++ API is an example to do inference for a single image at a time.

**Comment by uCedar** [comment]
@yashnv Yes, `infer.cpp` is for a single image. Now I am trying to do inference for Multiple pictures at a time.

**Comment by uCedar** [comment]
> I don't understand your question What do you mean by?:
>  how to infer one batch of images at the same time?
>The C++ API is an example to do inference for a single image at a time.

@yashnv Thanks for your reply.
Yes, infer.cpp is for a single image. I mean how to do inference for Multiple pictures at a time.

**Comment by yashnv** [comment]
You can use the Python interface: https://github.com/NVIDIA/retinanet-examples#inference

The C++ API is an example of how to do inference via C++, not intended to be a replica of the same steps taken for python. We encourage users to take the base example given in C++ and extend to match their use case.

**Comment by adithya-p** [comment]
@yashnv I am trying to perform inference on two images at a time. I ensured that I am allocating memory based on the batch size of images and changed the line in [engine.cpp](https://github.com/NVIDIA/retinanet-examples/blob/master/csrc/engine.cpp#L189) to `_context->enqueue(2, buffers.data(), _stream, nullptr); ` where **2** is the batch size but this isn't working. @yashnv Can you please point out where exactly should I make those changes so that it'll work for batch size > 1?

**Comment by yashnv** [comment]
Which branch are you using? What docker container version? What is you driver version? What platform(GPU)?

**Comment by adithya-p** [comment]
@yashnv Here are the details you asked for,
Branch - master
Docker Container Version - 20.02
Driver Version - 440
Platform - GTX 1650

**Comment by yashnv** [comment]
You don't need to make any changes, if you are using the master branch. Use the Python interface to infer on 2 images.
`odtk infer engine.plan --images /path/to/images/`

**Comment by adithya-p** [comment]
@yashnv I know it works with the Python interface but I am having trouble to replicate the same with cppapi. I was wondering if you could point me in the right direction so that I can make those changes and proceed?

**Comment by yashnv** [comment]
Because TRT7 uses explicit batch, you can't just switch back to `enqueue` from `enqueuev2`. You need to provide one image at a time as a stream of inputs, for multiple images. Think of it as a loop. 

> The C++ API is an example of how to do inference via C++, not intended to be a replica of the same steps taken for python. We encourage users to take the base example given in C++ and extend to match their use case.

If you want the same functionality as python just check the code for python interface, and replicate in C++.

**Comment by adithya-p** [comment]
> If you want the same functionality as python just check the code for python interface, and replicate in C++.
I am trying to do that. When I am trying to get a correlation between [infer.py](https://github.com/NVIDIA/retinanet-examples/blob/master/retinanet/infer.py) and [infer.cpp](https://github.com/NVIDIA/retinanet-examples/blob/master/extras/cppapi/infer.cpp) or [infervideo.cpp](https://github.com/NVIDIA/retinanet-examples/blob/master/extras/cppapi/infervideo.cpp), I found that the only way how infer.py is analogous to cppapi - infer.cpp or infervideo.cpp is the linchpin that they both perform inference. With DALI in the picture in case of former, things like - CUDA Memory allocations, Host to Device and vice versa buffer transfers are very abstract. Can you point out what are the changes and where to make them so that multi-batch inference is possible with cppapi?

> Because TRT7 uses explicit batch, you can't just switch back to enqueue from enqueuev2. You need to provide one image at a time as a stream of inputs, for multiple images. Think of it as a loop

With batchSize as parameter for [virtual bool nvinfer1::IExecutionContext::execute( int batchSize, void ** bindings)](https://docs.nvidia.com/deeplearning/sdk/tensorrt-api/c_api/classnvinfer1_1_1_i_execution_context.html#a1fba6d417077b30a270d623119d02731), I thought tuning this might work. It worked with DetectNet and SSD.

**Comment by yashnv** [comment]
For starters, there are 2 ways to go about this:

- Use a loop for inferring, this is easy but the memory transfer from H2D and D2H will always be a bottleneck, this is one of the primary reasons why using the C++ API is an example, not a full solution

- The more complicated way (but obviously more efficient than the previous one): 
The [C++ Torch Data API](https://pytorch.org/cppdocs/api/dir_torch_csrc_api_include_torch_data.html#dir-torch-csrc-api-include-torch-data), try to read through our `retinanet/data.py` code and replicate.

If you do succeed you are always welcome to open a pull request, which will be reveiwed.
