### ISSUE TITLE
How to create checkpoint during training?

### ISSUE THREAD

**Issue by zardadi** [NVIDIA/retinanet-examples#156]
I'm not sure this is an issue, but I need to create checkpoints every 5000 iterations. Does anyone know what the easiest way is to create checkpoints. It's a really cool feature to have when we run training for a long time and can save the model every often for testing.

**Comment by james-nvidia** [comment]
@zardadi Thank you for the suggestion. That's something that we would like to introduce in the future. This is an open source project, so please send a PR if you implement it yourself. Otherwise we'll treat this as a feature request.
In the mean time, you can either periodically copy the model `.pth` file, as it saves out every minute, or you can use a bash script to train in 5k chunks, copying the model each time.

I'll close this issue, but I'll add a comment when we've added this feature.
