### ISSUE TITLE
Class Ids

### ISSUE THREAD

**Issue by pravn** [NVIDIA/retinanet-examples#172]
I am trying to infer the objects from class ids printed out in detections.json. Are these the 'same' as in coco? I am inclined to think that they are not. 

For one thing, I am trying to detect chairs. The detections themselves seem to be spot on (it draws good bounding boxes around object of interest). But the ids that it prints out are off. It gives me a class id of 56, which in COCO apparently seems to refer to the food category of broccoli(!). 

Also, the detections are consistent across different network backbones (resnet 152, 50, 34, 18) and across devices in that we get the same result in both the desktop gpu and in the jetson xavier agx devices.

**Comment by yashnv** [comment]
Hi the categories themselves are evaluated from Pycocotools.
Read more about this issue here: https://tech.amikelive.com/node-718/what-object-categories-labels-are-in-coco-dataset/

Check out the missing labels in the table for COCO2017. There are 5 missing classes before Chair(62) and Broccoli(56).
`62 - 5 = 57`, and the labels are 0-idexed(not 1-indexed as shown in the table), which means that 57 -> 56, interpreted as Broccoli.

We will investigate into this.

**Comment by james-nvidia** [comment]
@pravn what inference command are you using? If you don't provide `--annotations` during inference then `odtk` will sequentially number the classes, so they will not match the original COCO classes.

**Comment by james-nvidia** [comment]
Has this solved your problem?

**Comment by pravn** [comment]
@james-nvidia @yashnv Thank you for your hints. For now, I can hard code my object id as suggested, but this is not exactly ideal for other objects. 

Using `--annotations ` with coco validation set gives me the 'correct' result for a chair image (000000027620.jpg, object id of 62). This, together wirh @yashnv 's comments about missing labels validates detections. 

However, I think it still does not fix issues for quantized inference with cppapi on the jetson which is what I would really like to do. The way it stands, it would be a non-trivial exercise to backtrack the object name from the id.

**Comment by yashnv** [comment]
Why don't you use deepstream for the inference on Xavier? I fyou have Jetpack 4.3, you can use 19.10 branch for that.

By quantized infer, do you mean INT8? Because you will need to do some extra work for INT8 inference on Xavier. You will need to provide calibration batches in `export.cpp` to produce the INT8 engine plan and the INT8 Calibration cache.

**Comment by pravn** [comment]
I've not tried deepstream API (thank you for the tip). 

And yes, as you say, I can get it to quantize to int8 by giving it a few images to calibrate, and adding them to infer.cpp.

**Comment by yashnv** [comment]
Closing this now.
