### ISSUE TITLE
correct ground truth for annotation while using rotated-box training

### ISSUE THREAD

**Issue by bipulkumar22** [NVIDIA/retinanet-examples#174]
I see the documentation mentions `xmin,ymin,w,h and theta (in radians)` to be used in training. I have four points labeled for object detection. I am using  opencv `cv2.minAreaRect(box)` to get the angles in degrees and converting to radians while using the four labeled point to get `xmin,ymin,w,h`. Is this the right approach to train the rotated-box model

**Comment by piseabhijeet** [comment]
Hi @james-nvidia 

This is a very good suite of functions and quite useful too.

Can you also share the function for shuffling the order of corners in the best possible manner (instead of trial and errors, maybe by some mathematics prior, give the best order to the function)?

It would be a value add :)

Thanks
