### ISSUE TITLE
Can I use this repo locally without a docker container? I cloned the repo, what do I do next?

### ISSUE THREAD

**Issue by aditjha** [NVIDIA/retinanet-examples#204]

**Comment by yashnv** [comment]
Hello, we don't provide instructions for using this repository outside docker because it is difficult/time consuming to install and configure all the different install requirements in this repository.

**Comment by zhifanlight** [comment]
@aditjha I trained and tested in success without docker. steps to reproduce
1. install nvidia-dali by conda, install nvidia-apex by pip
2. remove engine-related code (csrc/* code, retinanet/*py import lines, setup.py), since no tensorrt in my server
3. in this repo root, run `python setup.py install` to install odtk
4. just use odtk as README.md
