### ISSUE TITLE
Custom backbones

### ISSUE THREAD

**Issue by ivanpanshin** [NVIDIA/retinanet-examples#265]
Is there any way to add custom backbones (for example, GeNet), so that the ONNX->TRT convertation with quantization doesn't break?

**Comment by ivanpanshin** [comment]
Another similar question: any way to get rid of FPN, so that the model gets lighter and faster on edge devices?

**Comment by yashnv** [comment]
Getting custom backbones to train and produce decent mAP are not trivial, and need a lot of experimentation. Moreover, once they give decent results, converting them to TRT is also not so trivial. FPN is major part of this repo, I don't see why we would want to remove it, try to make the backbone lighter instead of removing the FPN
