### ISSUE TITLE
could you please provide your retinanet_rn50fpn.pth

### ISSUE THREAD

**Issue by haima1998** [NVIDIA/retinanet-examples#27]
could you please provide your retinanet_rn50fpn.pth, I  can not train the result as you

**Comment by monocongo** [comment]
I would also like to have access to this file. My understanding is that for fine-tuning the model for a new object class we need to first train the model using the full COCO dataset in order to produce this file which can then be used as a basis for the fine-tuning (further-training) the model. Is this correct? If so then it seems that once this file is created then sharing it for reuse by all will save everyone else the trouble of recreating it. Or am I missing something obvious?

Thanks in advance for any help with this, and for making this project available in the first place.

**Comment by florischabert** [comment]
We just released pre-trained models (on COCO2017), check out https://github.com/NVIDIA/retinanet-examples/releases/tag/19.04

**Comment by monocongo** [comment]
Thank you, very helpful!

**Comment by haima1998** [comment]
Thank you very much!
