### ISSUE TITLE
Faster inference on TX2

### ISSUE THREAD

**Issue by Maxfashko** [NVIDIA/retinanet-examples#47]
Hi. My config:
Jetson TX2 with JetPack 4.2  (CUDA 10, cuDNN 7.3.1, TensorRT 5.0.3, OpenCV 3.3.1)
After assembling the cppapi, I checked the speed of the inference on the model by resnet50 at the image resolution of 1280 * 800. The speed of the test results ranges from 0.5-0.6 s.
What are the ways to speed up the inference model by 2-4 times with the current resolution? In this case, if we do not change the number of classifiers and regressors (let's leave it as it is 256). On personal experience, I know that reducing layers of classifiers and regressors can accelerate the inference by an average of 20% without losing accuracy (if we are dealing with large anchors)

**Comment by Maxfashko** [comment]
@florischabert Do you have any thoughts on this?

**Comment by mbufi** [comment]
@Maxfashko With any of the other object detection algos i've used in the past, reducing the number of detections the network spits out before NMS is huge. I have done it with many 2 stage detectors and seen speed ups of over 5 times.

**Comment by Maxfashko** [comment]
@mbufi Do you mean that you have reduced the layers of classification?

**Comment by pkashinkunti** [comment]
In general, since the TX2 is based on the Pascal GPU architecture, it will be harder to get acceleration from using reduced precision (FP16 or INT8) inference in TRT since it does not have Tensor Cores.

From your original post it looks like you are using a ResNet50 backbone: using a lighter weight backbone like ResNet18 could potentially help lower inference latency (at the cost of detection accuracy). 

Although you mention you would prefer to keep the input size as is, you could consider training and optimizing your model at a smaller input image size (again, potentially sacrificing some accuracy).
