### ISSUE TITLE
CUDA9 for retinanet-examples

### ISSUE THREAD

**Issue by YanhuaCheng** [NVIDIA/retinanet-examples#65]
Hi, I only have cuda9 on my machine. How can I run the code?

**Comment by yashnv** [comment]
I would suggest you run this code using NVIDIA's container as mentioned in the installation steps, because this repository depends on multiple components that come preconfigured with the container.

You can pull the conatiner using `docker pull nvcr.io/nvidia/pytorch:19.05-py3`, and then follw the steps.
